import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {publications,projects} from '../src/content.ts';
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const map=`<svg class="research-graphic" viewBox="0 0 660 370" role="img" aria-label="Conceptual map from a generative model to interacting agents in a simulation environment"><g class="grid"><path d="M30 30H630V310H30Z M30 100H630 M30 170H630 M30 240H630 M130 30V310 M230 30V310 M330 30V310 M430 30V310 M530 30V310"/></g><g class="terrain"><path d="M10 265C90 350 118 112 217 142S360 360 456 242S603 280 650 90 M0 232C105 315 150 91 223 110S355 320 480 208S591 244 660 55 M0 199C97 284 156 60 234 78S381 300 505 172S602 210 660 22 M15 175C112 210 136 33 252 43S390 262 514 140S590 145 640 7 M34 142C155 184 192 18 295 41S402 224 508 102S596 130 650 0"/></g><g class="route"><path d="M102 190L282 105L397 184L545 94 M282 105L298 263L397 184L539 280 M397 184L545 94L539 280L298 263"/></g><g class="node"><circle cx="102" cy="190" r="30"/><circle cx="282" cy="105" r="18"/><circle cx="298" cy="263" r="14"/><circle cx="397" cy="184" r="24"/><circle cx="545" cy="94" r="17"/><circle cx="539" cy="280" r="17"/></g><g stroke="#d3e46b" fill="none"><path d="M89 182H111 M100 182V202H114 M100 192H112"/><path d="M274 105H290 M282 97V113 M389 176H405V192H389Z"/></g><text x="48" y="245">MODEL</text><text x="274" y="52">AGENTS / INTERACTIONS</text><text x="350" y="350">SIMULATION ENVIRONMENT</text><text class="tiny" x="30" y="335">01 — GENERATE</text><text class="tiny" x="160" y="335">02 — ACT</text></svg>`;
const releaseRoot=fileURLToPath(new URL('../',import.meta.url));
const conceptRoot=path.join(releaseRoot,'public');
const outputRoot=path.join(releaseRoot,'dist');
fs.rmSync(outputRoot,{recursive:true,force:true});
fs.mkdirSync(outputRoot,{recursive:true});
fs.cpSync(conceptRoot,outputRoot,{recursive:true});
const manifests=['src/figures.json'];
const visualSources=new Map();
for(const file of manifests){const full=path.join(releaseRoot,file);if(!fs.existsSync(full))continue;const raw=JSON.parse(fs.readFileSync(full,'utf8'));const rows=Array.isArray(raw)?raw:raw.figures??raw.results??raw.items??[];for(const row of rows){if(row.id)visualSources.set(row.id,row);}}
function sourceFor(id){return visualSources.get(id)??visualSources.get({'agentsociety':'agentsociety-paper','opencity':'opencity-paper'}[id]);}
function sourceImage(id,title,sourceUrl,kind='paper'){
 const item=sourceFor(id);const asset=item?.asset_path?path.join(conceptRoot,item.asset_path):null;
 if(!asset||!fs.existsSync(asset))return `<div class="work-image-pending"><span>Source ${kind==='paper'?'figure':'image'}<br>pending</span><a href="${esc(sourceUrl)}">View original ↗</a></div>`;
 const relative=path.relative(conceptRoot,asset).split(path.sep).join('/');
 const version=item.version_label??item.source_version??item.version??'';
 const number=item.figure_number??item.figure;const figureName=number?`Figure ${String(number).replace(/^Figure\s*/i,'')}`:'Paper figure';
 const label=kind==='paper'?figureName:item.kind==='ui-screenshot'?'Actual interface':item.kind==='repository-documentation'?'SDK documentation':figureName;
 const caption=item.kind==='repository-documentation'?'Actual public SDK documentation; no graphical application UI is published.':item.kind==='ui-screenshot'?'Public repository interface screenshot.':`${figureName}${item.page?` · PDF page ${item.page}`:''}${version?` · ${version}`:''}`;
 const link=item.source_url??item.pdf_url??sourceUrl;
 return `<a class="work-image" href="${esc(link)}" data-figure="${esc(relative)}" data-figure-title="${esc(title)}" data-figure-caption="${esc(caption)}" aria-label="Open representative ${kind==='paper'?'paper figure':'image'} for ${esc(title)}"><img src="${esc(relative)}" alt="${esc(label)} for ${esc(title)}" loading="lazy"><span class="work-image-label">${esc(label)} <span>↗</span></span></a>`;
}
function figureCredit(id){const item=sourceFor(id);if(!item?.asset_path)return '';const version=item.version_label??item.version??'';return `<p class="figure-credit">${esc(version)}</p>`;}
const pubRows=publications.map(p=>`<article class="pub-row"><div class="year">${esc(p.year)}</div><div class="pub-figure">${sourceImage(p.id,p.title,p.url)}</div><div class="pub-text"><h3><a href="${esc(p.url)}">${esc(p.title)} ↗</a></h3><p class="topics">${esc(p.topics)}</p>${figureCredit(p.id)}</div><p class="pub-meta">${esc(p.venue)}<span>${esc(p.role)}</span></p></article>`).join('');
const projectRows=projects.slice(1).map((p,i)=>`<article class="project-row"><span class="mono">0${i+2}</span><div class="project-row-image">${sourceImage(p.id,p.title,p.links[0].url,'project')}</div><div class="project-row-copy"><h3>${esc(p.title)}</h3><p>${esc(p.description)}</p></div><a class="arrow" href="${esc(p.links[0].url)}" aria-label="Explore ${esc(p.title)}">↗</a></article>`).join('');
const html=`<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Yuwei Yan’s research and projects in Generative Model, Agent System, and Simulation. PhD at HKUST (Guangzhou)."><link rel="canonical" href="https://pinkgranite.github.io/"><meta name="robots" content="index,follow"><meta name="theme-color" content="#183c36"><meta property="og:type" content="website"><meta property="og:title" content="Yuwei Yan · Research & Systems"><meta property="og:description" content="Generative Model · Agent System · Simulation"><meta property="og:url" content="https://pinkgranite.github.io/"><meta property="og:image" content="https://pinkgranite.github.io/social-preview.png"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="favicon.svg" type="image/svg+xml"><script type="application/ld+json">{"@context":"https://schema.org","@type":"Person","name":"Yuwei Yan","url":"https://pinkgranite.github.io/","sameAs":["https://github.com/PinkGranite"],"knowsAbout":["Generative Model","Agent System","Simulation"]}</script><title>Yuwei Yan · Research & Systems</title><link rel="stylesheet" href="concept.css"></head><body><a class="skip-link" href="#research">Skip to research</a>
<div class="wrap"><header><a class="brand" href="#">Yuwei Yan<i></i></a><nav aria-label="Main"><a href="#research">Research</a><a href="#publications">Publications</a><a href="#projects">Projects</a><a href="#person">The person ↗</a></nav></header>
<main><section class="hero"><div class="hero-meta mono"><span>Researcher / builder / explorer</span><span>PhD · HKUST (Guangzhou)</span></div><h1 class="hero-name">Yuwei <span>Yan.</span></h1><div class="photo-sequence" id="photographs" data-photo-sequence><div class="photo-pin"><div class="hero-grid"><figure class="photo-figure" style="margin:0" aria-describedby="photo-description"><div class="hero-photo photo-composition" data-photo-composition><div class="photo-layer photo-alpine" aria-hidden="true"><img src="assets/alpine.webp" alt=""></div><div class="photo-layer photo-cafe-layer" aria-hidden="true"><img src="assets/cafe.webp" alt=""></div><div class="photo-layer photo-stage-layer" aria-hidden="true"><img src="assets/stage.webp" alt=""></div><div class="frame-corner"></div><span class="composition-index mono" aria-hidden="true">01 / 03</span></div><figcaption class="photo-caption"><span class="photo-current" data-photo-caption>01 / A wider perspective</span><div class="photo-controls" aria-label="Photograph controls"><button type="button" class="photo-arrow" data-photo-prev aria-label="Previous photograph composition">←</button><div class="photo-pips" role="group" aria-label="Choose a photograph composition"><button type="button" data-photo-select="0" aria-label="Mountain composition" aria-pressed="true"><span></span></button><button type="button" data-photo-select="1" aria-label="Café composition" aria-pressed="false"><span></span></button><button type="button" data-photo-select="2" aria-label="Stage composition" aria-pressed="false"><span></span></button></div><button type="button" class="photo-arrow" data-photo-next aria-label="Next photograph composition">→</button></div></figcaption><div class="photo-foot"><span data-photo-hint>Photographs from my collection</span><button type="button" class="photo-motion" data-photo-motion aria-pressed="false" hidden>Pause photo motion</button></div><span id="photo-description" class="sr-only">One composed region shows three photographs: Yuwei in a meadow beside a mountain ridge, seated at a café overlooking hills, and holding a microphone on a stage. Scroll to reveal the compositions, or use the photograph controls.</span><span class="sr-only" data-photo-announcement aria-live="polite"></span></figure><div class="hero-copy"><div><h2>Models become agents.<br>Agents inhabit worlds.</h2><p>I’m Yuwei. My research spans Generative Model, Agent System, and Simulation — connecting capabilities, interactions, and environments.</p><a class="anchor" href="#research">Explore my research <span class="arrow">↘</span></a></div><p class="small">Research, open-source systems, and the curiosity that connects them.</p></div></div></div></div><div class="hero-bottom"><span>Curiosity, in theory and in the world.</span><span>Scroll to explore ↓</span></div></section></main></div>
<div class="focus-bar"><div class="wrap"><span class="mono">Research focus</span><span>Generative Model</span><b>↗</b><span>Agent System</span><b>↗</b><span>Simulation</span><b>↗</b></div></div>
<section class="research" id="research" tabindex="-1"><div class="wrap"><div class="section-label mono"><span>01 / Research</span><span>Capabilities → interactions → environments</span></div><div class="research-top"><h2>From a model<br>to a world.</h2><p>I study the connections between models that generate, agents that reason and act, and environments in which behavior can be explored.</p></div><div class="research-layout"><div>${map}<div class="graphic-key"><span>Conceptual research map</span><span>Three connected areas / 01–03</span></div></div><div class="research-stages"><article class="research-stage"><span class="mono">01 / Generate</span><h3>Generative Model</h3><p>Generative capabilities, reinforced reasoning, and world modeling.</p></article><article class="research-stage"><span class="mono">02 / Act</span><h3>Agent System</h3><p>Reasoning, action, and interaction — connected into workflows and larger systems.</p></article><article class="research-stage"><span class="mono">03 / Simulate</span><h3>Simulation</h3><p>Social behavior and urban activity, studied through agents in an environment.</p></article></div></div></div></section>
<section class="publications" id="publications"><div class="wrap"><div class="section-label mono"><span>02 / Publications</span><span>Published work & preprints</span></div><div class="section-head"><h2>The research<br><em>record.</em></h2><p>A complete list of thirteen distinct works, with publication venues and author roles kept visible.</p></div><div class="publication-controls"><div class="filters"><span class="filter">All works</span><span class="filter">First / co-first</span><span class="filter">Peer-reviewed</span></div><span>13 distinct works · Google Scholar ↗</span></div>${pubRows}<p class="pub-note">Figures open at a larger size with source links. Preprint figures are identified separately from final publication metadata. Preprint and final versions are grouped as one work. </p></div></section>
<section class="projects" id="projects"><div class="wrap"><div class="section-label mono"><span>03 / Projects</span><span>Selected open-source & research systems</span></div><div class="section-head"><h2>Ideas,<br>in <em>working form.</em></h2><p>Research questions become systems to inspect, use, and build upon. AgentSociety leads this collection.</p></div><article class="project-lead"><div class="project-lead-visual sourced-project-visual">${sourceImage('agentsociety','AgentSociety',projects[0].links[0].url,'project')}</div><div><span class="mono">01 / Research platform</span><h3>AgentSociety</h3><p>${esc(projects[0].description)}</p><p class="role">Co-first author · iFuture 2026</p><a class="anchor" href="${esc(projects[0].links[0].url)}">Explore the research <span class="arrow">↗</span></a></div></article><div class="project-list">${projectRows}</div></div></section>
<section class="person person-summary" id="person"><div class="wrap"><div class="section-label mono"><span>04 / The person</span><span>Beyond the research</span></div><div class="person-head"><h2>Different places.<br>The same <em>curiosity.</em></h2><div><p>The photographs live together in one changing composition at the top of the page: a wider perspective, a quieter moment, and another kind of expression.</p><a class="anchor" href="#photographs">Revisit the photographs <span class="arrow">↑</span></a></div></div></div></section><section class="contact"><div class="wrap"><div class="section-label mono"><span>05 / Connect</span><span>Research & collaboration</span></div><div class="contact-grid"><h2>Let’s compare<br><em>worldviews.</em></h2><div class="contact-links"><a href="https://github.com/PinkGranite">GitHub <span>↗</span></a><a href="#publications">Research publications <span>↗</span></a><a href="#">Back to the top <span>↑</span></a></div></div><div class="contact-bottom"><span>Yuwei Yan / Field & Systems</span><span>© Yuwei Yan · 2026</span></div></div></section><dialog class="figure-dialog" aria-labelledby="figure-title"><div class="figure-dialog-head"><h2 id="figure-title"></h2><button type="button" class="figure-close" aria-label="Close figure">×</button></div><img class="figure-full" alt=""><div class="figure-dialog-caption"><p></p><a target="_blank" rel="noopener">View original source ↗</a></div></dialog><script type="module" src="photo-sequence.js"></script><script type="module" src="figures.js"></script></body></html>`;
fs.writeFileSync(path.join(outputRoot,'index.html'),html);
console.log('Built approved homepage: 13 publications, 4 projects, 10 source paper figures and 3 pending.');
