export interface Publication {
  id: string; title: string; year: string; venue: string; role: string;
  first: boolean; reviewed: boolean; url: string; code: string; topics: string;
  versions?: {label:string;url:string}[];
  note?: string;
}
// Scholar profile read in local Chrome: 15 records, grouped into 13 distinct works.
// Final publisher metadata takes precedence over stale preprint labels.
export const publications: Publication[] = [
  {id:'agentsociety-paper',title:'AgentSociety: Large-Scale Simulation of LLM-Driven Generative Agents Advances Understanding of Human Behaviors and Society',year:'2026',venue:'iFuture · 2026',role:'Co-first author',first:true,reviewed:true,url:'https://www.sciopen.com/article/10.26599/IF.2026.9710004',code:'',topics:'Generative agents · Human behavior',versions:[{label:'2025 preprint',url:'https://arxiv.org/abs/2502.08691'}],note:'Equal contribution with Jinghua Piao and Jun Zhang. Original platform research.'},
  {id:'opencity-paper',title:'Designing A Scalable LLM Agent Framework for Large-scale Urban Segregation Simulation',year:'2026',venue:'KDD 2026',role:'Co-first author',first:true,reviewed:true,url:'https://doi.org/10.1145/3770855.3818944',code:'https://github.com/tsinghua-fib-lab/OpenCity',topics:'OpenCity · Urban simulation',versions:[{label:'OpenCity preprint · 2024',url:'https://arxiv.org/abs/2410.21286'}],note:'Equal contribution with Qingbin Zeng. The OpenCity preprint and final KDD paper are grouped as one work.'},
  {id:'embodied-world-models',title:'A Survey of Embodied World Models',year:'2026',venue:'Preprints.org · Preprint',role:'Co-author',first:false,reviewed:false,url:'https://doi.org/10.20944/preprints202604.0928.v2',code:'https://github.com/tsinghua-fib-lab/Awesome-Embodied-World-Model',topics:'Embodied AI · World models'},
  {id:'agentrecbench',title:'AgentRecBench: Benchmarking LLM Agent-based Personalized Recommender Systems',year:'2025',venue:'NeurIPS 2025 · Datasets & Benchmarks',role:'Co-author',first:false,reviewed:true,url:'https://proceedings.neurips.cc/paper_files/paper/2025/hash/e2d6f7249add096e26679eade1b4cc6f-Abstract-Datasets_and_Benchmarks_Track.html',code:'',topics:'Recommender systems · Agent benchmarks',versions:[{label:'Preprint',url:'https://arxiv.org/abs/2505.19623'}],note:'Conference year: 2025. Google Scholar indexes the proceedings record in 2026.'},
  {id:'reasoning-survey',title:'Toward Large Reasoning Models: A Survey of Reinforced Reasoning with Large Language Models',year:'2025',venue:'Patterns · 6(10), 101370',role:'Co-author',first:false,reviewed:true,url:'https://doi.org/10.1016/j.patter.2025.101370',code:'',topics:'Reinforced reasoning · Language models',versions:[{label:'Preprint',url:'https://arxiv.org/abs/2501.09686'}]},
  {id:'workflow',title:'Simulating Generative Social Agents via Theory-Informed Workflow Design',year:'2025',venue:'arXiv preprint',role:'First author',first:true,reviewed:false,url:'https://arxiv.org/abs/2508.08726',code:'',topics:'Social agents · Workflow design'},
  {id:'experiments',title:'Exploring Large Language Model Agents for Piloting Social Experiments',year:'2025',venue:'COLM 2025',role:'Second author',first:false,reviewed:true,url:'https://arxiv.org/abs/2508.08678',code:'',topics:'Social experiments · LLM agents'},
  {id:'framework',title:'A Parallelized Framework for Simulating Large-Scale LLM Agents with Realistic Environments and Interactions',year:'2025',venue:'ACL 2025 · Industry',role:'Second author',first:false,reviewed:true,url:'https://aclanthology.org/2025.acl-industry.94/',code:'',topics:'Multi-agent systems · Simulation'},
  {id:'challenge',title:'AgentSociety Challenge: Designing LLM Agents for User Modeling and Recommendation on Web Platforms',year:'2025',venue:'WWW 2025 · Companion',role:'First author',first:true,reviewed:true,url:'https://doi.org/10.1145/3701716.3719233',code:'https://tsinghua-fib-lab.github.io/AgentSocietyChallenge/',topics:'User modeling · Recommendation'},
  {id:'international-perceptions',title:'The Roots of International Perceptions: Simulating US Attitude Changes Towards China with LLM Agents',year:'2025',venue:'arXiv preprint',role:'Co-author',first:false,reviewed:false,url:'https://arxiv.org/abs/2508.08837',code:'',topics:'Social simulation · International perceptions',note:'Also indexed as “Debiasing International Attitudes: LLM Agents for Simulating US-China Perception Changes”; both records link to arXiv:2508.08837.'},
  {id:'dids',title:'DIDS: A Distributed Inference Framework with Dynamic Scheduling Capability',year:'2025',venue:'Future Generation Computer Systems · 162, 107459',role:'First author',first:true,reviewed:true,url:'https://www.sciencedirect.com/science/article/pii/S0167739X2400400X',code:'',topics:'Distributed inference · Dynamic scheduling'},
  {id:'coala',title:'COALA: A Compiler-Assisted Adaptive Library Routines Allocation Framework for Heterogeneous Systems',year:'2024',venue:'IEEE Transactions on Computers · 73(7), 1724–1737',role:'Co-author',first:false,reviewed:true,url:'https://doi.org/10.1109/TC.2024.3385269',code:'https://github.com/e2mcc/coala',topics:'Compiler optimization · Heterogeneous systems'},
  {id:'mobisim-bench',title:'MobiSim-Bench: A Multi-Perspective Benchmark for Evaluating LLM-Agent-Based Human Mobility Simulation',year:'—',venue:'Manuscript',role:'Second author',first:false,reviewed:false,url:'https://openreview.net/forum?id=3QFvAXuNl7',code:'https://github.com/tsinghua-fib-lab/MobiSim-Bench',topics:'Human mobility · Agent benchmarks',note:'Listed without a year or venue in Google Scholar. No conference acceptance is asserted.'},
];
export const projects = [
  { id: 'agentsociety', title: 'AgentSociety', subtitle: 'A lens on behavior, interaction, and society.', type: 'Research platform', role: 'Co-first author · iFuture 2026', className: 'society', description: 'Generative agents, realistic environments, and social experiments in one research platform.', question: 'What can agent-based simulation reveal about human behavior and social systems?', approach: 'The original AgentSociety platform couples LLM-driven generative agents with a realistic environment and supports social experiments. Related work examines parallelized simulation and theory-informed agent workflows.', contribution: 'Co-first author, with equal contribution, on the iFuture 2026 AgentSociety paper. Second author on the ACL 2025 Industry framework paper; first author of the theory-informed workflow preprint and AgentSociety Challenge paper.', artifact: 'Published AgentSociety research, a simulation framework, and the WWW 2025 Companion challenge.', links: [{label:'Published paper',url:'https://www.sciopen.com/article/10.26599/IF.2026.9710004'},{label:'ACL framework',url:'https://aclanthology.org/2025.acl-industry.94/'},{label:'Challenge',url:'https://tsinghua-fib-lab.github.io/AgentSocietyChallenge/'}] },
  { id: 'intelliworld', title: 'IntelliWorld', subtitle: 'Knowledge with a traceable path to evidence.', type: 'Research knowledge system', role: 'Open-source project', className: 'evidence', description: 'Connecting source excerpts, assertions, and conflicting evidence into a research knowledge system.', question: 'How can research knowledge stay connected to the evidence behind it?', approach: 'IntelliWorld organizes source excerpts and assertion graphs, preserves conflicting evidence, and uses hybrid retrieval to support research exploration.', contribution: 'A public project on my GitHub, with documentation and interface examples describing an evidence-traceable research workflow.', artifact: 'Public source code and README. The diagram summarizes the documented workflow.', links: [{label:'Explore repository',url:'https://github.com/PinkGranite/IntelliWorld'}] },
  { id: 'easypaper', title: 'EasyPaper', subtitle: 'A collaborative workflow for academic writing.', type: 'Multi-agent writing system', role: 'Open-source project', className: 'paper', description: 'Multi-agent planning, writing, review, and LaTeX production for academic work.', question: 'How can multiple agents support a structured academic-writing process?', approach: 'EasyPaper separates planning, writing, and review into coordinated stages, with citation validation, LaTeX output, and optional visual review.', contribution: 'A public project on my GitHub documenting a multi-agent academic-writing workflow and its implementation.', artifact: 'Public source code and usage documentation.', links: [{label:'Explore repository',url:'https://github.com/PinkGranite/EasyPaper'}] },
  { id: 'opencity', title: 'OpenCity', subtitle: 'From individual agents to urban activity.', type: 'Research platform', role: 'Co-first author · KDD 2026', className: 'city', description: 'A scalable LLM-agent framework for urban activity and large-scale urban segregation simulation.', question: 'How can language-model agents participate in a realistic urban environment?', approach: 'OpenCity brings agent behavior and urban activity simulation into a shared platform, connecting individual decisions with their surrounding environment.', contribution: 'Co-first author, with equal contribution, on the KDD 2026 paper “Designing A Scalable LLM Agent Framework for Large-scale Urban Segregation Simulation.” First author on its earlier OpenCity preprint.', artifact: 'KDD 2026 paper, the earlier OpenCity preprint, and open-source implementation.', links: [{label:'KDD paper',url:'https://doi.org/10.1145/3770855.3818944'},{label:'View code',url:'https://github.com/tsinghua-fib-lab/OpenCity'},{label:'Publication entry',url:'#opencity-paper'}] },
];
